### ISSUE TITLE
Problems with /island join when updating to FTB Infinity Skyblock 1.1.0

### ISSUE THREAD

**Issue by Yabdat** [TheCricket/FTB-Islands#18]
Updated my FTB Infinity Skyblock server to 1.1.0 today, and ran into a few problems. 

First the /island join command didnt work, said the island didnt exist. Did some research, and found on FTB forums that island with capital letters didnt work anymore, and that I should rename the island with /island rename.
This worked on 4 out of 6 islands on my server for some reason..

If i tried to join one of the 2 that it didnt work on, i get 'An unknown error occurred while attempting to perform this command' on the client, and this error on the server console log:

22:53:33 Couldn't process command: 'island join pixelparty'

22:53:33 java.lang.NullPointerException
at com.cricketcraft.ftbisland.IslandCreator.joinIsland(IslandCreator.java:86) ~[IslandCreator.class:?]
at com.cricketcraft.ftbisland.SpawnIslandCommand.func_71515_b(SpawnIslandCommand.java:77) ~[SpawnIslandCommand.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

The island in question was called PixelParty when i made it on Skyblock 1.0.4.

And Island called CreatorBurden was renamed to creatorburden without any problems.

**Comment by TheCricket** [comment]
idk who gave you info but they are wrong

**Comment by Yabdat** [comment]
Oh? This is where I found it.

http://forum.feed-the-beast.com/threads/1-1-0-updating-server-losing-ability-to-join-islands.151181/

Anyway, the base problem is still here, since I updated the server islands with a capital letters come up as 'no island with that name' or whatever the exact notice is. 

Island without a capital letter in the name still works, and 4 of 6 island with a capital letter works when I used the /island rename command. 

Its not a very huge problem at my server, since its a small one for friends. I just setup /warp commands for all the islands.
But the command is still not working entirely good, thats why I made this bug report.

**Comment by TheCricket** [comment]
I mean yes thats a way around it but properly creating fixes the file

**Comment by Yabdat** [comment]
What do you mean properly creating fixes the file?

**Comment by TheCricket** [comment]
./island create <name>

**Comment by Yabdat** [comment]
So recreating the island fixes it? Ok.
