### ISSUE TITLE
Cannot create island

### ISSUE THREAD

**Issue by OCDiary** [TheCricket/FTB-Islands#23]
Im trying to use the mod for the first time and cannot create an island? The logs says:
[00:25:28] [Server thread/ERROR]: Couldn't process command: 'island_create ocdiary'
java.lang.NullPointerException
    at com.cricketcraft.ftbisland.IslandCreator.createIsland(IslandCreator.java:41) ~[IslandCreator.class:?]
    at com.cricketcraft.ftbisland.commands.CreateIslandsCommand.func_71515_b(CreateIslandsCommand.java:61) ~[CreateIslandsCommand.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

I have tried capitals in the name too so 'OCDiary' but still nothing. In game it says "An unknown error occurred while attempting to perform this command". I am using the new SkyFactory 2.5 server files, which I updated to the latest version also.
Thanks for your help
OC
<3

![ingame](https://cloud.githubusercontent.com/assets/10181128/15342791/026ceac6-1c90-11e6-9404-a66897b4c0ef.png)
![log](https://cloud.githubusercontent.com/assets/10181128/15342790/026ca426-1c90-11e6-96fb-c6bdf48dd247.png)

**Comment by kolatra** [comment]
Sorry which version of FTB Islands is this? Has Sky Factory already included it?

**Comment by OCDiary** [comment]
Hi Kolatra,
The version of islands is 1.2.1, which i believe is the latest? And no it was not included as standard, I added it as need it for a stream group server. Multiple streamers so more islands needed, it worked perfectly in the Infinity Skyblock Evolved modpack so thought why not just add it to SF2.5. I also noticed the lack of spawn in SF2.5. In Infinity Skyblock Evolved (ISE) it had a spawn platform. Is that the issue? Sorry I have hunted high and low before posting here <3 Oh and one final thing as a side note, the command 'island create' is not recognised (which it is in ISE), you have to use 'island_create'.
Thanks so much for the help
OC

**Comment by kolatra** [comment]
I was able to reproduce this, and am looking into it now.

**Comment by OCDiary** [comment]
Awesome thanks so much for the speedy response etc!

**Comment by kolatra** [comment]
After investigating, I have found the underlying issue, I am trying to work around it now.
