### ISSUE TITLE
Islands setspawn error

### ISSUE THREAD

**Issue by mich4075** [TheCricket/FTB-Islands#26]
hey 

I get a error when I try to use /island_setspawn 

What is wrong ?

Please help

```
> 
> [08:09:54] [Server thread/ERROR]: Couldn't process command: 'island_setspawn michael'
> java.lang.ArrayIndexOutOfBoundsException: 1
> at com.cricketcraft.ftbisland.commands.SetIslandSpawnCommand.func_71515_b(SetIslandSpawnCommand.java:33) ~[SetIslandSpawnCommand.class:?]
> at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
> at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
> at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
> at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
> at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
> at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
> at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by LezChap** [comment]
Right now the command looks like it's a bit borked...try adding the X Y Z coordinates to the command syntax.  Instead of using "/island_setspawn michael" you need to type "/island_setspawn michael X Y Z" (where those coordinates represent the whole-number values you want the spawn to be set to).  Currently it doesn't appear the command is using the player/command's location to set the X, Y, and Z coordinates if they're not provided.

**Comment by mich4075** [comment]
It still make the same error when I use "/island_setspawn michael -999 67 1000"

```
[20:02:16] [Server thread/ERROR]: Couldn't process command: 'island_setspawn guffy4075 -999 67 1000'
java.lang.NullPointerException
at com.cricketcraft.ftbisland.commands.SetIslandSpawnCommand.func_71515_b(SetIslandSpawnCommand.java:33) ~[SetIslandSpawnCommand.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by LezChap** [comment]
That's actually a different error, but it's in the same line of the code.  I'm not sure what's actually causing this one from a quick glance at the code...I might tinker around later and see if I can figure it out, if the devs don't get to it first. :)

**Comment by LezChap** [comment]
Also, as a manual fix for now, you should be able to edit the json file on the server, located at /local/islands.json

**Comment by kolatra** [comment]
Fairly certain I fixed this, if this is still an issue please let me know.
