### ISSUE TITLE
Bug: NullPointerException when trying to join a island that is not created.

### ISSUE THREAD

**Issue by StoneLegion** [TheCricket/FTB-Islands#4]
You get this when trying join an none existing island. 

[22:28:05 INFO]: Kane_Hart issued server command: /island join NoKanye3
[22:28:05 ERROR]: Couldn't process command: 'island join NoKanye3'
java.lang.NullPointerException
        at com.cricketcraft.ftbisland.IslandCreator.joinIsland(IslandCreator.java:72) ~[IslandCreator.class:?]
        at com.cricketcraft.ftbisland.SpawnIslandCommand.func_71515_b(SpawnIslandCommand.java:67) ~[SpawnIslandCommand.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53) [CraftSimpleCommandMap.class:1.7.10-1614.50]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:733) [CraftServer.class:1.7.10-1614.50]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1328) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1103) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by kolatra** [comment]
I can't reproduce this one in the dev environment, it may have been fixed from the latest commit. However I found a different exception that I am currently debugging.
